# Generated by Django 6.0.2 on 2026-02-28 08:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='Unique ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('personal_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', message='Phone number must contain only digits.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='identity.person')),
                ('rank', models.CharField(choices=[('professor', 'Professor'), ('associate', 'Associate Professor'), ('assistant', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('instructor', 'Instructor')], max_length=20)),
                ('employment_category', models.CharField(choices=[('tenured', 'Tenured'), ('adjunct', 'Adjunct/Part-time'), ('visiting', 'Visiting Researcher')], max_length=20)),
                ('appointment_start_date', models.DateField()),
                ('primary_department', models.CharField(max_length=100)),
                ('secondary_departments', models.TextField(blank=True, help_text='Comma separated departments')),
                ('office', models.CharField(blank=True, max_length=100)),
                ('phd_institution', models.CharField(blank=True, max_length=200)),
                ('research_areas', models.TextField(blank=True)),
                ('habilitation', models.BooleanField(default=False)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('hourly', 'Hourly')], max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('teaching_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='identity.person')),
                ('assigned_department', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3')], max_length=10)),
                ('entry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='identity.person')),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('highschool_diploma', models.JSONField(blank=True, null=True)),
                ('major', models.CharField(max_length=100)),
                ('entry_year', models.PositiveIntegerField()),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('scholarship', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('was_student', 'Was student'), ('same_person', 'Same person')], default='was_student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='identity.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='identity.person')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='identity.person')),
            ],
        ),
    ]
